/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    identityPoolId: 'ap-southeast-1:40ee4c75-f632-4f8e-bded-2b9a18ca8a03',
    region: 'ap-southeast-1',
    identityPoolRegion: 'ap-southeast-1',
    userPoolId: 'ap-southeast-1_aqQtRtXHC',
    userPoolWebClientId: '4h0493r1teghsua00vajka5ajl',
};

export default awsmobile;
