export default Actions = {
  //handle loading
  HANDLE_LOADING: 'HANDLE_LOADING',

  //handle success
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  CLEAR_SUCCESS: 'CLEAR_SUCCESS',

  //handle error
  REQUEST_ERROR: 'REQUEST_ERROR',
  REQUEST_ERROR_RAW: 'REQUEST_ERROR_RAW',
  CLEAR_ERROR: 'CLEAR_ERROR',

  LOGIN_AGAIN: 'LOGIN_AGAIN',

  //login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  USER_REGISTER: 'USER_REGISTER',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

  /**
   *  Note: Sau khi đăng nhập acc Cognito, lấy username và email trả về để tạo 1 acc customer bên woo
   *        Nếu acc customer bên woo đã tồn tại thì get list customers và filter ra acc cần dùng
   */
  
  // create customer on Woo
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',

  // filter current customer on Woo
  FILTER_CURRENT_CUSTOMER_SUCCESS: 'FILTER_CURRENT_CUSTOMER_SUCCESS',

  SET_USER_INFO: 'SET_USER_INFO',

  //update avatar url for cognito user attribute
  SET_AVATAR_URL: 'SET_AVATAR_URL',

  // cart
  HANDLE_EDIT_CART: 'HANDLE_EDIT_CART',
  GET_CART: 'GET_CART',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',

  // update profile: include information & delivery address
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',

  // products list
  GET_LIST_PRODUCTS_REQUEST: 'GET_LIST_PRODUCTS_REQUEST',
  GET_LIST_PRODUCTS_SUCCESS: 'GET_LIST_PRODUCTS_SUCCESS',
  GET_LIST_PRODUCTS_FAILURE: 'GET_LIST_PRODUCTS_FAILURE',
  GET_MORE_LIST_PRODUCTS_REQUEST: 'GET_MORE_LIST_PRODUCTS_REQUEST',
  GET_MORE_LIST_PRODUCTS_SUCCESS: 'GET_MORE_LIST_PRODUCTS_SUCCESS',
  GET_MORE_LIST_PRODUCTS_FAILURE: 'GET_MORE_LIST_PRODUCTS_FAILURE',

  // home products list
  GET_LIST_PRODUCTS_TODAY_OFFERS_SUCCESS:
    'GET_LIST_PRODUCTS_TODAY_OFFERS_SUCCESS',
  GET_LIST_PRODUCTS_NEWEST_SUCCESS: 'GET_LIST_PRODUCTS_NEWEST_SUCCESS',

  // category
  GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',

  // product review
  GET_PRODUCT_REVIEW_REQUEST: 'GET_PRODUCT_REVIEW_REQUEST',
  GET_PRODUCT_REVIEW_SUCCESS: 'GET_PRODUCT_REVIEW_SUCCESS',
  GET_PRODUCT_REVIEW_FAILURE: 'GET_PRODUCT_REVIEW_FAILURE',

  SEND_PRODUCT_REVIEW_SUCCESS: 'SEND_PRODUCT_REVIEW_SUCCESS',

  // list posts
  GET_LIST_POSTS_REQUEST: 'GET_LIST_POSTS_REQUEST',
  GET_LIST_POSTS_SUCCESS: 'GET_LIST_POSTS_SUCCESS',
  GET_LIST_POSTS_FAILURE: 'GET_LIST_POSTS_FAILURE',
  GET_MORE_LIST_POSTS_REQUEST: 'GET_MORE_LIST_POSTS_REQUEST',
  GET_MORE_LIST_POSTS_SUCCESS: 'GET_MORE_LIST_POSTS_SUCCESS',
  GET_MORE_LIST_POSTS_FAILURE: 'GET_MORE_LIST_POSTS_FAILURE',
  COMMENT_POST_SUCCESS: 'COMMENT_POST_SUCCESS',

  // create order
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',

  // payment method
  GET_PAYMENT_METHOD_SUCCESS: 'GET_PAYMENT_METHOD_SUCCESS',

  // history order
  GET_HISTORY_ORDER_REQUEST: 'GET_HISTORY_ORDER_REQUEST',
  GET_HISTORY_ORDER_SUCCESS: 'GET_HISTORY_ORDER_SUCCESS',
  GET_HISTORY_ORDER_FAILURE: 'GET_HISTORY_ORDER_FAILURE',
  GET_MORE_HISTORY_ORDER_REQUEST: 'GET_MORE_HISTORY_ORDER_REQUEST',
  GET_MORE_HISTORY_ORDER_SUCCESS: 'GET_MORE_HISTORY_ORDER_SUCCESS',
  GET_MORE_HISTORY_ORDER_FAILURE: 'GET_MORE_HISTORY_ORDER_FAILURE',

  // home banner
  GET_HOME_BANNER_SUCCESS: 'GET_HOME_BANNER_SUCCESS',

  // change language
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
}
